name: Deploy Weather App

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create config.js with secret key
        run: |
          echo "const param = { url: 'https://api.openweathermap.org/data/2.5/', appid: '${{ secrets.WEATHER_API_KEY }}' };" > config.js

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .  # деплоїмо корінь
